configured_endpoints: 50
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/serval--inc-dash%2Fserval-c166b33c7bc7fbf9b9c4972e7237daffddbd44fde8acbdea7bda770ca812236f.yml
openapi_spec_hash: 2cfcbf6906200e02dfd4f54953bffdc7
config_hash: 0e0c10d6f633eda39e8e238628cd058d
