configured_endpoints: 60
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/serval--inc-dash%2Fserval-9d6fadfa962f6fd20a81c63c0505caab9f1ac48dc4b0b3d1ba2f1fc66bd7c802.yml
openapi_spec_hash: 410b16df58bff5fe3a867082e18ab28b
config_hash: bc198eabca5c1bd38f30e4d6ebaa4ed0
