#!/usr/bin/env bash

set -euo pipefail

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/ServalHQ/serval-go,github.com/stainless-sdks/serval-go"

go build -o terraform-provider-serval
